### ISSUE TITLE
Mejorar el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m3-evaluacion-intermedia-valerialp#1]
Buen trabajo @valerialp !!

Algunas pistas para acabarlo:

- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Mueve el `li` fuera del componente 'Pokemon', de esta manera Pokemon es un componente con una tarjeta que podemos usar en diferentes sitios y no solo dentro de un `ul`
- [x] Añade un título a la página (Mi lista de Pokemons)
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Elimina el código comentado
- [x] Añade estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [ ] Publica en Github Pages
- [x] Elimina archivos sin usar y sus referencias

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by valerialp** [comment]
Hello! perform the tasks of the checklist but the bonus did not manage to pass the information to the global state

**Comment by nasivuela** [comment]
Bien juagado @valerialp 

Cierro issue, no sin antes dejarte unas recomendaciones de última hora, ya que creo que le falta algo de mimo:

- Ojo con las propTypes, has puesto en App las de PokeList, y en PokeList las de Pokemon. Recuerda que las proptypes deben checkear las props que le llegan al componente, no las que envía a sus hijas.
- El archivo `ArrPokemon.js` no es un componente. ¿Y si lo movemos a otra carpeta? La puedes llamar data, utils, constants...
- ¡La etiqueta `img` se autocierra!
- Ojo en App, que estás pasando un método por props al listado que no existe!
- GithubPages
